### ISSUE TITLE
The widget doesn't show properly on the taskbar.

### ISSUE THREAD

**Issue by unixfox** [MakG10/plasma-applet-bitcoin-price#1]
The widget works great on the desktop but not on the taskbar, it overlaps another extension:
![](https://i.imgur.com/2mOeT1X.png)

**Comment by MakG10** [comment]
Thanks for the feedback, the issue should be fixed now. Plasmoid package is available here on GitHub: https://github.com/MakG10/plasma-applet-bitcoin-price/blob/master/bitcoin-price.plasmoid and on https://www.opendesktop.org/p/1188643/

**Comment by unixfox** [comment]
Thank you for trying to fix this issue but it is still present: ![](https://i.imgur.com/wFTUkB7.png)
And uncheck "Show text" seems to do nothing:
![](https://i.imgur.com/8V68REw.png)

**Comment by unixfox** [comment]
Fixed
